"""Where are we in the semester, and what is filed for the weeks already taught?

    python src/week.py            # this week
    python src/week.py --all      # the whole semester at a glance

Future weeks are never reported as missing — an empty folder almost always
means the lecturer has not published anything yet.

Each week's README.md is generated by canvas_sync.py, so "record" in the status
line means Canvas has been synced for that week, not that anyone wrote prose.

The plan below is provisional until `python src/canvas_sync.py` has read the
real one off Mitt UiB. Canvas is the source of truth; update PLAN to match it.
"""

from __future__ import annotations

import argparse
from datetime import date

from paths import ROOT, TUTORIAL

YEAR = 2026

# uke -> (topic, tutorial week that covers it).
# INF122 is one track, unlike DAT158 — no -ml/-alg split on the folders.
PLAN: dict[int, tuple[str, int | None]] = {
    34: ("(ikkje kunngjort enno)", 1),
    35: ("(ikkje kunngjort enno)", 2),
    36: ("(ikkje kunngjort enno)", 3),
    37: ("(ikkje kunngjort enno)", 4),
    38: ("(ikkje kunngjort enno)", 5),
    39: ("(ikkje kunngjort enno)", 6),
    40: ("(ikkje kunngjort enno)", 7),
    41: ("(ikkje kunngjort enno)", 8),
    42: ("(ikkje kunngjort enno)", 9),
    43: ("(ikkje kunngjort enno)", 10),
    44: ("(ikkje kunngjort enno)", 11),
    45: ("(ikkje kunngjort enno)", 12),
    46: ("(ikkje kunngjort enno)", None),
    47: ("(ikkje kunngjort enno)", None),
}

MONTHS = {1: "jan", 2: "feb", 3: "mar", 4: "apr", 5: "mai", 6: "jun",
          7: "jul", 8: "aug", 9: "sep", 10: "okt", 11: "nov", 12: "des"}


def dates(uke: int) -> str:
    """"17. - 23. aug" — derived, so there is no date table to get wrong."""
    mon = date.fromisocalendar(YEAR, uke, 1)
    sun = date.fromisocalendar(YEAR, uke, 7)
    if mon.month == sun.month:
        return f"{mon.day}. - {sun.day}. {MONTHS[sun.month]}"
    return f"{mon.day}. {MONTHS[mon.month]} - {sun.day}. {MONTHS[sun.month]}"


# Kept as a mapping so canvas_sync can use it the same way DAT158's did.
DATES = {uke: dates(uke) for uke in PLAN}


def folder(uke: int):
    return ROOT / "weeks" / f"uke{uke}"


def tutorial_folder(uke: int):
    """The tutorial week that goes with this teaching week, if there is one."""
    _, tut = PLAN[uke]
    return TUTORIAL / f"week{tut:02d}" if tut else None


def survey(uke: int) -> dict:
    """What exists for a week. Counts, not judgements."""
    d = folder(uke)

    def count(sub):
        p = d / sub
        return len([f for f in p.iterdir() if f.name != ".gitkeep"]) if p.exists() else 0

    tut = tutorial_folder(uke)
    return {
        "record": (d / "README.md").exists(),
        "slides": count("slides"),
        "code": count("code"),
        "exercises": count("exercises"),
        "lesson": bool(tut and (tut / "LESSON.md").exists()),
    }


def line(uke: int, current: int) -> str:
    topic, tut = PLAN[uke]
    s = survey(uke)
    marker = ">" if uke == current else " "
    when = "future" if uke > current else ("NOW" if uke == current else "past")

    bits = [
        "record" if s["record"] else "-",
        f"{s['slides']} slides" if s["slides"] else "-",
        f"{s['code']} code" if s["code"] else "-",
        f"{s['exercises']} exc" if s["exercises"] else "-",
        (f"tut{tut:02d}" + ("" if s["lesson"] else " (no lesson)")) if tut else "-",
    ]
    return f"{marker} uke{uke} {when:<6} [{' | '.join(bits)}]  {topic[:40]}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--all", action="store_true", help="show every week")
    args = ap.parse_args()

    today = date.today()
    current = today.isocalendar().week

    print(f"Today: {today:%Y-%m-%d} - ISO week {current}")

    if current < min(PLAN):
        print(f"Semester starts in uke {min(PLAN)}.")
        return 0
    if current > max(PLAN):
        print(f"Teaching ended in uke {max(PLAN)}. Exam period - see exam/.")
        return 0

    topic, tut = PLAN[current]
    print(f"Current: uke{current} - {topic}")
    print(f"Folder:  weeks/uke{current}/")
    if tut:
        print(f"Tutorial: tutorial/week{tut:02d}/  (./check.sh {tut})")
    print()

    weeks = sorted(PLAN) if args.all else [u for u in sorted(PLAN) if u <= current]
    for uke in weeks:
        print(line(uke, current))

    # Only ever chase weeks that have already happened.
    gaps = [u for u in sorted(PLAN) if u <= current and not survey(u)["slides"]]
    if gaps:
        print(
            "\nNo material filed for: "
            + ", ".join(f"uke{u}" for u in gaps)
            + "\nIf the lecturer hasn't published it yet, that's expected - ignore."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
