"""Where are we in the semester, and what is filed for the weeks already taught?

    .venv/bin/python src/week.py            # this week
    .venv/bin/python src/week.py --all      # the whole semester at a glance

Future weeks are never reported as missing — an empty folder almost always
means the lecturer has not published anything yet.

Each week's README.md is generated by canvas_sync.py, so "record" in the status
line means Canvas has been synced for that week, not that anyone wrote prose.

The plan below is provisional until `.venv/bin/python src/canvas_sync.py` has
read the real one off Mitt UiB. Canvas is the source of truth; update PLAN to
match it.
"""

from __future__ import annotations

import argparse
from datetime import date

from paths import ROOT, TUTORIAL

YEAR = 2026

# uke -> (topic, tutorial week that covers it).
# INF122 is one track, unlike DAT158 — no -ml/-alg split on the folders.
PLAN: dict[int, tuple[str, int | None]] = {
    # The lecturer's own "tentativ framdriftsplan", from
    # weeks/uke34/slides/1krav-plan+intro.pdf p.2. Chapter numbers are Hutton.
    # Where a topic spans several weeks his plan says so, and it is repeated
    # here rather than split, because that is what he wrote.
    #
    # The tutorial column is mine, not his: it points at the tutorial week whose
    # chapter the course is on. Weeks with no matching tutorial week say None —
    # parsing, type inference and the oblig have no tutorial material.
    34: ("kap. 1-2 (15) - intro, first steps", 1),
    35: ("kap. 3-4 - types and classes, defining functions", 2),
    # His plan said "kap. 3-4" for this week too, but the notes he published
    # for it are titled "[kap.4-5]" — patterns, lists and list comprehensions.
    # weeks/uke36/slides/3-func+list-handoutpdf.pdf p.1. Published beats
    # tentative, so the topic follows the slides; the tutorial week still says
    # 3 because Hutton 4 is where the week starts. Hutton 5 is week 4.
    36: ("kap. 4-5 - defining functions, list comprehensions", 3),
    37: ("kap. 5-8 - list comprehensions to declaring types", 4),
    38: ("kap. 5-8 - list comprehensions to declaring types", 5),
    39: ("kap. 5-8 - list comprehensions to declaring types", 6),
    # From uke40 on the topics follow what he published, not the tentative
    # plan: 7-IO-hand.pdf is course week 7, 8-grammatikk-hand.pdf is week 8,
    # and his announcement of 27 September puts unification and type inference
    # in the two to three weeks after IO, with the oblig announced around
    # mid-October. The tutorial column is unchanged — sheet N still lives in
    # tutorial week N.
    40: ("kap. 10 - interactive programming (IO)", 7),
    41: ("grammatikk og enkel parsing (forelesningsnotater!)", 8),
    42: ("unifikasjon + typeinferens (forelesningsnotater!), oblig kunngjøres ca. midt i oktober", 9),
    43: ("typeinferens (forelesningsnotater!)", 10),
    44: ("typeinferens, and the oblig opens", 11),
    45: ("Oblig (frist antakelig rundt 10. november)", None),
    46: ("Oblig (frist antakelig rundt 10. november)", None),
    47: ("resultater og gjennomgang av Oblig", None),
    48: ("spørsmål og svar", 12),
    49: ("**Eksamen 2. desember** - 3t skriftleg, ingen hjelpemiddel", None),
}

# The course numbers its own weeks from 1, and its filenames follow suit
# ("uke1.txt", "1krav-plan+intro.pdf"). Teaching started in ISO week 34 — the
# first lecture was Monday 17 August — so course week 1 is uke34.
#
# A mid-semester break shifts this. If the lecturer's "uke 8" lands in a week
# that PLAN says is something else, PLAN wins: fix the mapping here.
FIRST_TEACHING_WEEK = 34


def iso_week(number: int) -> int | None:
    """ISO week for a week number found in a filename, or None if off-plan.

    The lecturer uses both conventions: his plan says "uke 34" (ISO) while his
    files say "uke1.txt" (the course's first week, which is uke34). A number
    that is already a teaching week is taken at face value; anything smaller is
    counted forward from the first one.
    """
    if number in PLAN:
        return number
    uke = FIRST_TEACHING_WEEK + number - 1
    return uke if uke in PLAN else None


MONTHS = {1: "jan", 2: "feb", 3: "mar", 4: "apr", 5: "mai", 6: "jun",
          7: "jul", 8: "aug", 9: "sep", 10: "okt", 11: "nov", 12: "des"}


def dates(uke: int) -> str:
    """"17. - 23. aug" — derived, so there is no date table to get wrong."""
    mon = date.fromisocalendar(YEAR, uke, 1)
    sun = date.fromisocalendar(YEAR, uke, 7)
    if mon.month == sun.month:
        return f"{mon.day}. - {sun.day}. {MONTHS[sun.month]}"
    return f"{mon.day}. {MONTHS[mon.month]} - {sun.day}. {MONTHS[sun.month]}"


# Kept as a mapping so canvas_sync can use it the same way DAT158's did.
DATES = {uke: dates(uke) for uke in PLAN}


def folder(uke: int):
    return ROOT / "weeks" / f"uke{uke}"


def tutorial_folder(uke: int):
    """The tutorial week that goes with this teaching week, if there is one."""
    _, tut = PLAN[uke]
    return TUTORIAL / f"week{tut:02d}" if tut else None


def survey(uke: int) -> dict:
    """What exists for a week. Counts, not judgements."""
    d = folder(uke)

    def count(sub):
        p = d / sub
        return len([f for f in p.iterdir() if f.name != ".gitkeep"]) if p.exists() else 0

    tut = tutorial_folder(uke)
    return {
        "record": (d / "README.md").exists(),
        "slides": count("slides"),
        "code": count("code"),
        "exercises": count("exercises"),
        "lesson": bool(tut and (tut / "LESSON.md").exists()),
    }


def line(uke: int, current: int) -> str:
    topic, tut = PLAN[uke]
    s = survey(uke)
    marker = ">" if uke == current else " "
    when = "future" if uke > current else ("NOW" if uke == current else "past")

    bits = [
        "record" if s["record"] else "-",
        f"{s['slides']} slides" if s["slides"] else "-",
        f"{s['code']} code" if s["code"] else "-",
        f"{s['exercises']} exc" if s["exercises"] else "-",
        (f"tut{tut:02d}" + ("" if s["lesson"] else " (no lesson)")) if tut else "-",
    ]
    return f"{marker} uke{uke} {when:<6} [{' | '.join(bits)}]  {topic[:40]}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--all", action="store_true", help="show every week")
    args = ap.parse_args()

    today = date.today()
    current = today.isocalendar().week

    print(f"Today: {today:%Y-%m-%d} - ISO week {current}")

    if current < min(PLAN):
        print(f"Semester starts in uke {min(PLAN)}.")
        return 0
    if current > max(PLAN):
        print(f"Teaching ended in uke {max(PLAN)}. Exam period - see exam/.")
        return 0

    topic, tut = PLAN[current]
    print(f"Current: uke{current} - {topic}")
    print(f"Folder:  weeks/uke{current}/")
    if tut:
        print(f"Tutorial: tutorial/week{tut:02d}/  (./check.sh {tut})")
    print()

    weeks = sorted(PLAN) if args.all else [u for u in sorted(PLAN) if u <= current]
    for uke in weeks:
        print(line(uke, current))

    # Only ever chase weeks that have already happened.
    gaps = [u for u in sorted(PLAN) if u <= current and not survey(u)["slides"]]
    if gaps:
        print(
            "\nNo material filed for: "
            + ", ".join(f"uke{u}" for u in gaps)
            + "\nIf the lecturer hasn't published it yet, that's expected - ignore."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
